name: exscope
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - samtools=1.18
  - bedtools=2.31.1
  - mosdepth=0.3.6
  - pysam=0.22.0
  - pybedtools=0.9.1
  - gffutils=0.12
  - pygenometracks=3.7
  - matplotlib=3.5.1
  - numpy=1.24.3
  - pandas=1.5.3
  - pytest=7.4.3
  - black=23.12.1
  - mypy=1.7.1
  - pip=23.3.1
  - pip:
    - igv-reports
prefix: /home/taimoor/miniconda3/envs/exscope
